#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
#WORKDIR /app
#EXPOSE 5000
#ENV ASPNETCORE_URLS=http://*:5000

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /source
COPY ../*.sln .
COPY e-widencje.Api/*.csproj ./e-widencje.Api/
RUN dotnet restore
COPY e-widencje.Api/. ./e-widencje.Api/
WORKDIR /source/e-widencje.Api
#RUN dotnet build "e-widencje.Api.csproj" -c Release -o /app/build

#FROM build AS publish
RUN dotnet publish -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "e-widencje.Api.dll"]