version: '3.4'

services:
#  test-db:
#    image: postgres
#    container_name: test-db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    ports:
#      - 5433:5432
#    networks:
#      - test-network

  backend:
    image: ${DOCKER_REGISTRY-}e-widencje
    build:
      context: .
      dockerfile: e-widencje/Dockerfile

  client:
    image: client
    build:
      context: ./e-widencje/e-widencje/ClientApp
      dockerfile: Dockerfile

  proxy:
    image: nginx:mainline