version: '3.7'

services:
  test-db:
    image: postgres
    container_name: test-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    networks:
      - test-network

  e-widencje:
    image: ${DOCKER_REGISTRY-}e-widencje
    build:
      context: .
      dockerfile: e-widencje/Dockerfile
